name: Deploy Production
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PUBLISHPAT }}
          # Destination branch to push changes
          branch: main
          # Force the changes through
          # force: true
          # Change to the build directory before pushing

          repository: "ilri/rhomis-data-app"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          CI: false

      - name: Modify CNAME file to contain correct directory
        run: |
          file_contents=$(<./build/CNAME) &&
          echo "${file_contents//'TESTDOMAIN'/'rhomis.cgiar.org'}" > ./build/CNAME

      - name: Init new repo in build folder and commit generated files
        run: |
          cd build
          git init
          git add -A
          git config --local user.email "lgorman@turing.ac.uk"
          git config --local user.name "l-gorman"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PUBLISHPAT }}
          # Destination branch to push changes
          branch: gh-pages
          # Force the changes through
          # force: true
          # Change to the build directory before pushing
          directory: ./build
          repository: "ilri/rhomis-data-app"
